version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - APIFY_API_TOKEN=${APIFY_API_TOKEN}
      - X_USERNAMES=${X_USERNAMES}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    ports:
      - "3000:3000" 